Run simulation script started

diff --git a/axi4l-uart/scripts/run_sim b/axi4l-uart/scripts/run_sim
--- a/axi4l-uart/scripts/run_sim
+++ b/axi4l-uart/scripts/run_sim
@@ -1,7 +1,15 @@
 #!/bin/bash
 
-MODELSIM="$(readlink -f ./sim/modelsim.ini)"
-export MODELSIM
+err () {
+    local msg
+    msg="${1}"
+    printf 'Error: %s\n' "${msg}" >&2
+}
 
-vsim -c -voptargs=+acc -do 'log -r \*; run -all; exit' work.top
+source "../tools.conf" >/dev/null 2>&1 || \
+    { err "Could not import tool versions"; exit 1; }
 
+#vsim -c -voptargs=+acc -do 'log -r \*; run -all; exit' work.top
+
+echo $XILINX_SIMLIB_DIR
+echo $MODELSIM
